services:
  mongo:
    image: mongo:7
    container_name: juttax-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - juttax-mongo-data:/data/db

volumes:
  juttax-mongo-data:
